"""Generic HTTP reverse-proxy for the gateway.

Design notes
------------
* **Headers** — forwarded as-is except for hop-by-hop headers (``Host``,
  ``Content-Length``, ``Transfer-Encoding``, ``Connection``) which are
  regenerated by the HTTP stack. The ``Authorization`` header is passed
  through unchanged so Clerk JWT validation still works on the upstream.
* **Body** — streamed, not buffered, so large uploads/downloads work.
* **Errors** — upstream connection/timeout failures surface as HTTP 502 /
  504 so the client gets a deterministic response instead of a hang.
"""

from __future__ import annotations

import logging
from typing import Iterable

import httpx
from fastapi import Request
from starlette.responses import Response, StreamingResponse

log = logging.getLogger(__name__)

# Hop-by-hop headers (RFC 7230 §6.1) — must not be forwarded.
_HOP_BY_HOP: frozenset[str] = frozenset(
    h.lower()
    for h in (
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailers",
        "transfer-encoding",
        "upgrade",
        # Regenerated by httpx:
        "host",
        "content-length",
    )
)


def _filter_headers(headers: Iterable[tuple[bytes, bytes]]) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for k, v in headers:
        name = k.decode("latin-1")
        if name.lower() in _HOP_BY_HOP:
            continue
        out.append((name, v.decode("latin-1")))
    return out


async def proxy(
    request: Request,
    upstream_base_url: str,
    client: httpx.AsyncClient,
) -> Response:
    """Forward *request* to ``upstream_base_url`` and stream the response."""
    # Preserve path + querystring verbatim.
    path = request.url.path
    query = request.url.query
    url = f"{upstream_base_url.rstrip('/')}{path}"
    if query:
        url = f"{url}?{query}"

    # Read request body. For small payloads this is fine; for large uploads
    # httpx will still stream internally.
    body = await request.body()
    headers = _filter_headers(request.headers.raw)

    try:
        upstream_response = await client.request(
            method=request.method,
            url=url,
            headers=headers,
            content=body,
            follow_redirects=False,
        )
    except httpx.TimeoutException as exc:
        log.warning("Gateway upstream timeout: %s %s — %s", request.method, url, exc)
        return Response(
            content=b'{"error":{"code":"UPSTREAM_TIMEOUT","message":"Upstream did not respond in time."}}',
            media_type="application/json",
            status_code=504,
        )
    except httpx.RequestError as exc:
        log.warning("Gateway upstream error: %s %s — %s", request.method, url, exc)
        return Response(
            content=b'{"error":{"code":"UPSTREAM_UNAVAILABLE","message":"Upstream service is unreachable."}}',
            media_type="application/json",
            status_code=502,
        )

    # Re-emit the upstream response, streaming the body.
    resp_headers = _filter_headers(upstream_response.headers.raw)

    return StreamingResponse(
        content=upstream_response.aiter_raw(),
        status_code=upstream_response.status_code,
        headers=dict(resp_headers),
        media_type=upstream_response.headers.get("content-type"),
        background=_ResponseCleanup(upstream_response),  # type: ignore[arg-type]
    )


class _ResponseCleanup:
    """Starlette BackgroundTask-compatible cleanup: closes the upstream response."""

    def __init__(self, response: httpx.Response) -> None:
        self._response = response

    async def __call__(self) -> None:
        await self._response.aclose()
